projects:
  bookingsystem:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: kqkjyhdxuncdnlaejrjm34ua6m
      endpoints:
        prod: >-
          https://rc3c4aelnrebzoaawqjxkpxhhe.appsync-api.us-east-1.amazonaws.com/graphql
