// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:2ce2c86f-5af8-48d2-a6e0-8d769fb4bb53",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_nTGYRFTSV",
    "aws_user_pools_web_client_id": "1cvnaj5g87fdu1849d2p2vjcos",
    "aws_mobile_analytics_app_id": "ff970504587f40d6b898df8132e9db94",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://rc3c4aelnrebzoaawqjxkpxhhe.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-t3tdfjtizber3dwkdng3f3q3iq"
};


export default awsmobile;
