// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ddd6ce07-62c7-4912-9f12-8eba87187b87",
    "aws_cognito_region": "us-east-1",
    "aws_mobile_analytics_app_id": "aa185c7c458b4013b9a879b9d070fe33",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
